cookie:
  expiry_days: 30
  key: 5Qj9p36dMa
  name: kuzma_segment_cookie
credentials:
  usernames:
    loky217:
      email: loky21072001@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Ky Tran
      password: $2b$12$8O2u5jxchB.C9jCRjRZoKeWDN29fqrQSMe3G1oBkzGhXUu7D5Ay5a
    shopadmin:
      email: kuzma_vendor@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Kuzma Admin
      password: $2b$12$i4t.ukhffabAGWsRTIT60./oPZMdA82f.f8ZHKBjStJqwU6NW.EvW
pre-authorized:
  emails:
  - loky21072001@gmail.com
