[connections.warehouse]
dialect = "postgresql"
host = "localhost"
port = "5430"
database = "warehouse"
username = "postgres"
password = "2107"

[connections.segment]
dialect = "postgresql"
host = "localhost"
port = "5430"
database = "segmentation_2"
username = "postgres"
password = "2107"